### PR TITLE
WIP: further build automation

### PR DESCRIPTION
**Pull request by bbarker**
I believe there may be some issues here with having git repos nested (so be careful if you merge and run - I will look into it soon otherwise). However, this shows the gist of what I was hoping to do.

### CODE REVIEW

**Comment by githwxi** [comment]
Sorry, I was not clear about the usage of buildRelease.sh.
What I intended is to do something like this:

```shell
cd /tmp
sh $PATSHOME/share/SCRIPT/buildRelease.sh
```

Once the built packages are uploaded, the git-repos should be deleted:

```shell
rm -rf /tmp/ATS-Postiats /tmp/ATS-Postiats-contrib
```

**Comment by githwxi** [comment]
I manually incorporated some of your changes. There is no longer a need for git-merge. Thanks!

**Comment by bbarker** [comment]
Ah, I see - changes look good, I'll try it soon.

**Comment by bbarker** [comment]
@githwxi one thing I'm curious about; I had this line `$GIT checkout "tags/v${PATSVERSION}"` in there so the build could be done specifically based on a particular commit. This would allow you to tag a release (as seems to already be done), then there would be no ambiguity as to what should be in the built version.

**Comment by githwxi** [comment]
I see. Could you add it back and then issue a pull request. Thanks!

**Pull request closed without merging**
