### PR TITLE
Static array t0ype

### PR DESCRIPTION
**Pull request by ashalkhakov**
This is in response to issue #90 (the use-case I have in mind is implementing Google's MathFu in ATS2).

Some simple cases of static arrays work. Static arrays cannot be returned from functions (as in C), and they can be put into record fields.

This is half-baked, but it works for the simple case (see the fieldarr2 sample).

On a somewhat unrelated note, I've also added some functions to typeval.

### CODE REVIEW

**Comment by githwxi** [comment]
I added tieq_to_int1. It is called tieq2int. It is essentially the only function one needs: The rest is basically loop-unrolling that can be done by a competent optimizer at C-level or lower.

**Comment by githwxi** [comment]
As for arrays of fixed size, I plan to handle them based on some form meta-programming.
I do not yet have a very clear idea on this. I need to do experiments first.

**Comment by githwxi** [comment]
As for MathFu, I think having an interface (SATS) for MathFu in ATS should be enough. At least for now.

**Comment by ashalkhakov** [comment]
Re: MathFu: it's in C++, and it's also templated. If you take a look at [this](https://github.com/ashalkhakov/ATS-playground/blob/master/mathlib.dats), you'll find some of my experiments. Doing it with flat arrays is rather simple and requires no unsafe casts. The only issue is, flat arrays cannot be put into records even if their size is fixed. And with this approach it's very simple to provide vectors of, say, 5 dimensions (x,y,z coordinates, s, t texture coordinates), which can then be uploaded to the GPU.

**Comment by ashalkhakov** [comment]
Re: tieq2int1: nice! I wasn't quite sure about the naming.

**Comment by githwxi** [comment]
Say your want an array of size 5. Would this trick work:

abstype array_5_fixed(a:t@ype) // array_5_fixed needs to be properly defined in C
assume array_5_fixed(a:t@ype) = @[a][5]

**Comment by githwxi** [comment]
There is a tail-call optimization bug in patsopt. I add a line at the end of your code to circumvent this bug.
This is probably the cause of the crash you encountered.

implement(N)
loop<S(N)> {n} (pf | va, vb, vc, res) = {
//
prval TIEQS(pf) = pf
//
val pva = addr@(va)
and pvb = addr@(vb)
and pvc = addr@(vc)
and pres = addr@(res)
//
prval (pfva_at, pfva_arr1) = array_v_uncons (view@(va))
and (pfvb_at, pfvb_arr1) = array_v_uncons (view@(vb))
and (pfvc_at, pfvc_arr1) = array_v_uncons (view@(vc))
and (pfres_at, pfres_arr1) = array_v_uncons (view@(res))
//
val () = !pres := vec_map3$fwork<a> (!pva, !pvb, !pvc)
//
val (pfva_arr1 | pva_1) = viewptr_match (pfva_arr1 | ptr1_succ<a> (pva))
and (pfvb_arr1 | pvb_1) = viewptr_match (pfvb_arr1 | ptr1_succ<a> (pvb))
and (pfvc_arr1 | pvc_1) = viewptr_match (pfvc_arr1 | ptr1_succ<a> (pvc))
and (pfres_arr1 | pres_1) = viewptr_match (pfres_arr1 | ptr1_succ<a> (pres))
//
val () = loop<N> (pf | !pva_1, !pvb_1, !pvc_1, !pres_1)
//
prval () = view@(va) := array_v_cons (pfva_at, pfva_arr1)
and () = view@(vb) := array_v_cons (pfvb_at, pfvb_arr1)
and () = view@(vc) := array_v_cons (pfvc_at, pfvc_arr1)
and () = view@(res) := array_v_cons (pfres_at, pfres_arr1)
//
val () = ignoret(0)
//
} (* end of [loop<S(N)>] *)

**Comment by ashalkhakov** [comment]
Closing this down. I ended up following your suggestion with the $extype_struct (in fieldarr example). If anybody is interested, the code is in [ATS-playground](https://github.com/ashalkhakov/ATS-playground) repo (see `SHARE/vector.hats`).

I'm wondering about the metaprogramming part of your reply, though. What did you mean? Could you provide some pointers on what can be reasonably expected in the future?

**Comment by githwxi** [comment]
Thanks for the experiment!

I will try to re-evaluate the support for arrays of fixed size in ATS. 

By meta-programming, I mean a way to write code (in some form) that can generate ATS code.
For instance, if a datatype is declared, then a print function for the datatype can be automatically supplied.
In particular, I am thinking about a way to compile C into ATS. It would be really helpful if the first step described in the following aritcle can be done automatically or even semi-automatically:

http://bluishcoder.co.nz/2014/04/11/preventing-heartbleed-bugs-with-safe-languages.html

**Comment by bbarker** [comment]
I have a tangentially related comment. Over the weekend I ported the
IntelliJATS plugin from Java to Kotlin
<https://github.com/bbarker/IntelliJATS/tree/toKotlin> (a JVM-language from
the company that makes IntelliJ). It was very easy, because most of it
could be done automatically by the Kotlin-plugin for IntelliJ, and it is
very readable code. I'm sure that going from C to ATS could be done in a
similar way, though the end result may not be the most ideal of ATS code.
The same can be said for some of the Java->Kotlin conversions, but I
suspect the gap would be larger for C->ATS.

The Kotlin plugin is open source, so I just wanted to point it out as a
possible place to look for ideas.

On Wed, Mar 25, 2015 at 9:24 AM, Hongwei Xi <notifications@github.com>
wrote:

> Thanks for the experiment!
>
> I will try to re-evaluate the support for arrays of fixed size in ATS.
>
> By meta-programming, I mean a way to write code (in some form) that can
> generate ATS code.
> For instance, if a datatype is declared, then a print function for the
> datatype can be automatically supplied.
> In particular, I am thinking about a way to compile C into ATS. It would
> be really helpful if the first step described in the following aritcle can
> be done automatically or even semi-automatically:
>
>
> http://bluishcoder.co.nz/2014/04/11/preventing-heartbleed-bugs-with-safe-languages.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/githwxi/ATS-Postiats/pull/131#issuecomment-86022071>.
>



-- 
Brandon Barker
brandon.barker@gmail.com

**Comment by bbarker** [comment]
Also possibly applicable was ROSE; I think you had previously mentioned the
possibility of using it to go in the opposite direction ATS->LanguageX.
https://groups.google.com/d/msg/ats-lang-users/Iaj_kHSokRc/GIdPl6KcQ4IJ

On Wed, Mar 25, 2015 at 9:32 AM, Brandon Barker <brandon.barker@gmail.com>
wrote:

> I have a tangentially related comment. Over the weekend I ported the
> IntelliJATS plugin from Java to Kotlin
> <https://github.com/bbarker/IntelliJATS/tree/toKotlin> (a JVM-language
> from the company that makes IntelliJ). It was very easy, because most of it
> could be done automatically by the Kotlin-plugin for IntelliJ, and it is
> very readable code. I'm sure that going from C to ATS could be done in a
> similar way, though the end result may not be the most ideal of ATS code.
> The same can be said for some of the Java->Kotlin conversions, but I
> suspect the gap would be larger for C->ATS.
>
> The Kotlin plugin is open source, so I just wanted to point it out as a
> possible place to look for ideas.
>
> On Wed, Mar 25, 2015 at 9:24 AM, Hongwei Xi <notifications@github.com>
> wrote:
>
>> Thanks for the experiment!
>>
>> I will try to re-evaluate the support for arrays of fixed size in ATS.
>>
>> By meta-programming, I mean a way to write code (in some form) that can
>> generate ATS code.
>> For instance, if a datatype is declared, then a print function for the
>> datatype can be automatically supplied.
>> In particular, I am thinking about a way to compile C into ATS. It would
>> be really helpful if the first step described in the following aritcle can
>> be done automatically or even semi-automatically:
>>
>>
>> http://bluishcoder.co.nz/2014/04/11/preventing-heartbleed-bugs-with-safe-languages.html
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/githwxi/ATS-Postiats/pull/131#issuecomment-86022071>.
>>
>
>
>
> --
> Brandon Barker
> brandon.barker@gmail.com
>



-- 
Brandon Barker
brandon.barker@gmail.com

**Pull request closed without merging**
